[project]
name = 'Autonomous-Shipping-and-Logistics'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.shipping-logistics]
path = 'contracts/shipping-logistics.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
